# Generated by Django 4.2.1 on 2023-05-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_address_zip_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
