# Generated by Django 4.2.1 on 2023-05-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
